name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore api-web-services-dose-certa/api-web-services-dose-certa

    - name: Build
      run: dotnet build --no-restore --configuration Release api-web-services-dose-certa/api-web-services-dose-certa

    - name: Run
      run: dotnet run --no-build --configuration Release --project api-web-services-dose-certa/api-web-services-dose-certa/api-web-services-dose-certa.csproj
